# Generated by Django 4.0.6 on 2022-07-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_joint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='isVegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default='M', max_length=1),
        ),
    ]
